### ISSUE TITLE
Suggestion : Make a "hidden" character "War_Band" for all the account wide stuff

### ISSUE THREAD

**Issue by tealkami** [Thaoky/Altoholic_Retail#31]
Hi, first: thank you for your work, you are the best.

The suggestion: 
Right now everything is saved per character, but with Trader's Tender and now Warband Bank are account wide, so maybe make a "War_Band" character and make exceptions for Trader's Tender and things in Warband Bank and for future stuff, so everytime it read the data for those things it check/count/save as the "War_Band" character.

so in Summary Window/tab on top there would be character "War_Band" which you could delete too (if some database error happen) and would save the account wide stuff

It would make it more clear for some stuff, for example: When you check how much Trader's Tender you have, instead showing 15 characters with different values, it would only show "War_Band", same with Warband Bank item (which is right now "bugged" and counts the same item multiple times in the "total owned", like: I don't have "total owned 94000" Trader's Tender, or 3-4 the account wide gear in Warband BanK).

I did use the _ in example, because if someone have character with name "Warband", so it does mix up with errors

**Comment by Thaoky** [comment]
The trader's tender is fixed in 11.0.002, I expect at some point Blizzard will realize that transferring currencies makes no sense and will make most transferrable currencies account wide. My code is now ready for that.
The game and its API's are not in a state where I could simply do it the way you request, but I'll handle warband stuff separately (the recent big database update was a good move that made it easier to support the warband).
